### ISSUE TITLE
error when run the script

### ISSUE THREAD

**Issue by yqrashawn** [patrickward/jira-to-omnifocus#1]
```
  in "/Users/***/.jira-to-omnifocus.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/Users/***/.jira-to-omnifocus.yml", line 14, column 5
```

this is my .yml file.

```

---
jira:
        hostname: http://my.jira.server/
        username: ***
        password: ***
        jql: 'project="{***}" and assigneed = currentUser() and sprint in openSprints() ordered by priority desc '
        maxResults: 100
        showNotifications: true
        projects:
            - ***
        completedStatus:
            - Done
            - Closed
            - Resolved
    omnifocus:
        context: 'Office'
```
